### PR TITLE
Update .NET to 5.0

### PR DESCRIPTION
**Pull request by KarbonKitty**
This builds correctly on my machine, so I'd like to check against the automated builds, so I can try reproducing the problems locally. And solve them as well, hopefully. ;)

### CODE REVIEW

**Comment by KarbonKitty** [comment]
It seems that GitHub Actions flow fails because it's explicitly set to .NET Core 3.1 - there is 3.1 SDK being downloaded and used. I guess that there is an options somewhere to move it to 5.0, but it is probably only available to you. :) Azure Pipeline seems to complete without errors and with more or less the same warnings as my local version, so it probably is using .NET 5 already.

**Comment by ekolis** [comment]
Oh, yeah, I guess we don't need the Azure build anymore if we can get the GitHub Actions one working; I just added that a while back because GitHub Actions didn't support .NET or something... I'll try and set the action to use .NET 5 when I get a chance!

**Comment by ekolis** [comment]
I set the build action to .NET 5, but it looks like this PR is still using .NET Core 3.1 since that change was technically a change to the repo that you don't have in your branch. So you'll need to merge from my master branch to your branch in order to get that.

**Comment by ekolis** [comment]
The automated builds seem to be working, so that's good. We should probably do a bit of smoke testing just to make sure nothing major is broken, then I can merge your changes.

I wonder thought if this change would be dropping support for Linux, since .NET doesn't support WinForms on Linux, and Mono doesn't play nice with .NET 5 apps last I checked? I would like to update to a more modern UI framework that's also cross platform, but I'm not sure which to use...

**Comment by ekolis** [comment]
I played a few turns using this branch and tested features such as ship design, ship construction, movement, research, and combat simulations. Everything looks fine, apart from a few minor issues such as the component sort in the ship designer changing and the backgrounds of certain panels being gray instead of black. I'm gonna go ahead and merge this PR; at some point we can convert the csproj files to the new format and start implementing nullable reference types, but this is a good place to start from. I'm still a bit concerned about the loss of Linux support, but hopefully we should be able to come up with a better UI framework than WinForms that runs on a variety of operating systems...

**Comment by ekolis** [comment]
Huh, apparently I can't merge a pull request after I close it. OK then. I reopened it and I'll merge it and then close it again...

**Review by ekolis — APPROVED** [review]
I left a comment on the PR, didn't quite understand how reviews work here - I'm used to Azure DevOps at work! Everything should be good.

**Comment by KarbonKitty** [comment]
That's great that it works! I'll be taking a look at the other issues tomorrow and looking for something smaller to bite. ;) If time permits, I will also try looking at the WinForms project and maybe come up with some ideas for rewriting the presentation portion, too...

**Comment by ekolis** [comment]
Oh, that would be really cool! Thanks!

**Pull request merged**
